// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://byxjrxsnpjgtghgizuon.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5eGpyeHNucGpndGdoZ2l6dW9uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTQzOTksImV4cCI6MjA2NTU5MDM5OX0.8MdDExur0AR5O8eL_MYitBMSOjldKjNFXe7rXiA5Di8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);